from . import views
from django.urls import path
urlpatterns = [  
    path('',views.home, name='home'),
    path('about',views.about, name='about'),
    path('contact',views.contact, name='contact'),
    path('blog',views.blog, name='blog'),
    path('modal/<int:id>/',views.modal, name='modal'),
    path('redirect',views.redirect, name='redirect'),           
    path('signin',views.signin, name='signin'),          
    path('signin',views.signin, name='signin'),
    path('signup',views.signup, name='signup'),
    path('user_logout',views.user_logout, name='user_logout'),
    path('otp_login',views.otp_login, name='otp_login'),
    path('verify_otp',views.verify_otp, name='verify_otp'),
    path('profile',views.profile, name='profile'),
    path('edit_account',views.edit_account, name='edit_account'),
    path('edit_password',views.edit_password, name='edit_password'),
    path('del_customer_address',views.del_customer_address, name='del_customer_address'),
    path('edit_customer_address',views.edit_customer_address, name='edit_customer_address'),
    path('add_customer_address',views.add_customer_address, name='add_customer_address'),
    path('product',views.product, name='product'),
    path('add_product',views.add_product, name='add_product'),
    path('get_product',views.get_product, name='get_product'),
    path('edit_product',views.edit_product, name='edit_product'),
    path('delete_product',views.delete_product, name='delete_product'),  
    path('cart',views.cart, name='cart'),
    path('check_cart',views.check_cart, name='check_cart'),  
    path('modify_cart',views.modify_cart, name='modify_cart'), 
    path('del_cart_item',views.del_cart_item, name='del_cart_item'), 
    path('order',views.order, name='order'), 
    path('cancel_order',views.cancel_order, name='cancel_order'), 
    path('return_order',views.return_order, name='return_order'),
    path('order_info',views.order_info, name='order_info'),
    path('checkout',views.checkout, name='checkout'),
    path('razorpay_success',views.razorpay_success, name='razorpay_success'),
    path('paypal_success',views.paypal_success, name='paypal_success'),
    path('razorpay_failed',views.razorpay_failed, name='razorpay_failed'),
    path('create_invoice/<int:id>',views.create_invoice, name='create_invoice'),
    path('apply_coupon',views.apply_coupon, name='apply_coupon'),
    path('search',views.search, name='search'),
    path('wishlists',views.wishlists, name='wishlists'),
    path('remove_wishlists',views.remove_wishlists, name='remove_wishlists'),
    
]