from . import views
from django.urls import path
urlpatterns = [            
    path('',views.admin_signin, name='admin_signin'),
    path('dashboard',views.dashboard, name='dashboard'),
    path('signout',views.signout, name='signout'),
    path('products',views.products, name='products'),
    path('accounts',views.accounts, name='accounts'),
    path('filters',views.filters, name='filters'),
    path('edit_filters',views.edit_filters, name='edit_filters'),
    path('edit_category',views.edit_category, name='edit_category'),
    path('edit_size',views.edit_size, name='edit_size'),
    path('edit_color',views.edit_color, name='edit_color'),
    path('order_manage',views.order_manage, name='order_manage'),
    path('cancel_order_admin',views.cancel_order_admin, name='cancel_order_admin'),
    path('confirm_order_admin',views.confirm_order_admin, name='confirm_order_admin'),
    path('deliver_order_admin',views.deliver_order_admin, name='deliver_order_admin'),
    path('ship_order_admin',views.ship_order_admin, name='ship_order_admin'),
    path('refund_order',views.refund_order, name='refund_order'),
    path('customer_order/<int:id>',views.customer_order, name='customer_order'),
    path('get_data',views.get_data, name='get_data'),
    path('report',views.report, name='report'),
    path('daily_report',views.daily_report, name='daily_report'),
    path('monthly_report/<str:month>',views.monthly_report, name='monthly_report'),
    path('yearly_report/<str:year>',views.yearly_report, name='yearly_report'),
    path('filter_report/<str:from_date>/<str:to_date>',views.filter_report, name='filter_report'),
    path('download_report/<str:from_date>/<str:to_date>',views.download_report, name='download_report'),
    path('download_report_csv/<str:from_date>/<str:to_date>',views.download_report_csv, name='download_report_csv'),
    path('offer',views.offer, name='offer'),
    path('set_coupon',views.set_coupon, name='set_coupon'),
    path('set_category_offer',views.set_category_offer, name='set_category_offer'),
    path('set_product_offer',views.set_product_offer, name='set_product_offer'),
    path('cancel_offer',views.cancel_offer, name='cancel_offer'),
    path('monthly_order_report/<str:month>',views.monthly_order_report, name='monthly_order_report'),
]
